[project]
name = "poc-dpl-dagster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brice Schaffner", email = "brice.schaffner@swisstopo.ch" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
poc-dpl-dagster = "poc_dpl_dagster:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
