[project]
name = "first_tuto"
requires-python = ">=3.10,<3.15"
version = "0.1.0"
dependencies = [
    "dagster==1.13.17",
    "dagster-duckdb>=0.29.17",
    "dagster-k8s>=0.29.17",
    "dagster-postgres>=0.29.17",
]

[dependency-groups]
dev = [
    "dagster-dg-cli",
    "dagster-webserver",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "first_tuto"
registry_modules = [
    "first_tuto.components.*",
]


